/var/www/html in wordpress-for-tests should not be a volume
This directory is used for running tests; it is entirely ephemeral.

Also, having it as a volume causes the mkdir and chown in
./dev-env/wordpress-cli-image/Dockerfile
to not take effect (since the volume is mounted over
/var/www/html), resulting in the tests not being able to
write to /var/www/html since its not owned by www-data,
resulting in tests failing with this error:
```
Exception: Error executing cmd 'php '/tmp/wp-cli-latest-stable.phar' core download --path='/var/www/html/wptest' --version='4.9' --force --locale='en_US'' from working directory '/var/www/html/wptest':
Error: '/var/www/html/wptest/' is not writable by current user.
 in /opt/versionpress/tests/Automation/WpAutomation.php:621
```